Add APICurio guide for modifying and visualising kuadrant extensions
Kuadrant/kuadrantctl pull request #57
Opened 2024-03-05 19:56 UTC by david-martin

Closes https://github.com/Kuadrant/docs.kuadrant.io/issues/63

2024-03-06 09:37 UTC, jasonmadigan requested changes

2024-03-06 09:37 UTC, jasonmadigan commented on doc/openapi-apicurio.md
> +## Usin APICurio to edit an OpenAPI spec and visualise Kuadrant extensions
```suggestion
## Using APICurio to edit an OpenAPI spec and visualise Kuadrant extensions
```

2024-03-06 09:37 UTC, jasonmadigan commented on doc/openapi-apicurio.md
> +```
```suggestion
```yaml
info:
    x-kuadrant:
        route:
            name: petstore
            namespace: petstore
            hostnames:
                - 'petstore.example.com'
            parentRefs:
                -   name: prod-web
                    namespace: kuadrant-multi-cluster-gateways
                    kind: Gateway
```
```

2024-03-06 09:37 UTC, jasonmadigan commented on doc/openapi-apicurio.md
> +```
can probably remove the labelling stuff

2024-03-06 09:37 UTC, jasonmadigan commented on doc/openapi-apicurio.md
> +### Editing the spec
Before diving into editing, might be worth a pre-amble on OAS extensions, linking out to https://swagger.io/docs/specification/openapi-extensions/

2024-03-06 09:37 UTC, jasonmadigan commented on doc/openapi-apicurio.md
> +To generate a RateLimitPolicy for the API, add the following `x-kuadrant` block to a path in your spec,
```suggestion
To generate a `RateLimitPolicy` for the API, add the following `x-kuadrant` block to a path in your spec,
```

2024-03-06 09:37 UTC, jasonmadigan commented on doc/openapi-apicurio.md
> +To generate a RateLimitPolicy for the API, add the following `x-kuadrant` block to a path in your spec,
perhaps also a link to the RLP API dcs.

2024-03-06 09:37 UTC, jasonmadigan commented
taking shape, couple of comments added

2024-03-07 12:45 UTC, jasonmadigan commented
@david-martin this LGTM. It may be worth an eye from someone from Apicurio as well

2024-03-07 15:37 UTC, david-martin commented
> may be worth an eye from someone from Apicurio

@jasonmadigan Good suggestion.
Do you mind if you add lgtm etc.. and I can get a deploy preview link on the docs repo to share with them for review before it actually gets published?

2024-03-07 16:10 UTC, jasonmadigan commented
/lgtm
/approve

2024-03-07 16:16 UTC, david-martin commented
Merging manually. 
Auto merge not marking the GH review as good, but lgtm added

2024-03-07 16:16 UTC, merged