guide: CI/CD with Tekton
Kuadrant/kuadrantctl pull request #59
Opened 2024-03-07 17:18 UTC by jasonmadigan

2024-03-07 17:29 UTC, jasonmadigan commented
@david-martin  draft. I need to do an e2e spin through

2024-03-08 10:13 UTC, david-martin requested changes
Got the task to run, which some changes suggested above.
The task is failing at the moment. I haven't looked into why, but here's the status:

```
kubectl get taskrun -A
NAMESPACE                NAME                      SUCCEEDED   REASON                    STARTTIME   COMPLETIONTIME
kuadrantctl-ci-example   run-kuadrantctl-taskrun   False       TaskRunResolutionFailed   76s         76s
```

```
      message: 'error when listing tasks for taskRun run-kuadrantctl-taskrun: tasks.tekton.dev
        "run-kuadrantctl" not found'
```

events
```
kubectl -n kuadrantctl-ci-example get ev
LAST SEEN   TYPE      REASON                 OBJECT                                         MESSAGE
109s        Normal    Started                taskrun/run-kuadrantctl-taskrun
109s        Warning   Failed                 taskrun/run-kuadrantctl-taskrun                error when listing tasks for taskRun run-kuadrantctl-taskrun: tasks.tekton.dev "run-kuadrantctl" not found
109s        Warning   InternalError          taskrun/run-kuadrantctl-taskrun                1 error occurred:...
2m11s       Normal    WaitForFirstConsumer   persistentvolumeclaim/tekton-kuadrantctl-pvc   waiting for first consumer to be created before binding
```

2024-03-08 10:13 UTC, david-martin commented on doc/kuadrantctl-ci-cd.md
> +        kubectl apply -f ./generated-resources -n kuadrantctl-ci-example
```suggestion
  - name: apply-resources
    image: lachlanevenson/k8s-kubectl
    script: |
      cd $(workspaces.source.path)
      kubectl apply -f ./generated-resources -n kuadrantctl-ci-example
```
Indentation a little off here

2024-03-08 14:26 UTC, jasonmadigan commented
@david-martin this is actually runnable now. Added some steps to test.

2024-03-08 14:26 UTC, jasonmadigan commented on doc/kuadrantctl-ci-cd.md
> +- apiGroups: ["*"]
could probably narrow these

2024-03-08 14:27 UTC, jasonmadigan commented on doc/kuadrantctl-ci-cd.md
> +      image: alpine:latest
might be worth considering a kudrantctl image at some point with this stuff baked in.Could merge/shorten steps 3/4

2024-03-11 11:51 UTC, david-martin commented on doc/kuadrantctl-ci-cd.md
> +- (Tekton CLI `tkn`[https://tekton.dev/docs/cli/]) (optional) for easier interaction with Tekton resources.
Worth adding Kuadrant installed (and gateway api crds)?

2024-03-11 11:54 UTC, david-martin approved these changes
Small suggestion for pre-reqs, otherwise all good.

```bash
tkn tr list -n petstore
NAME                      STARTED          DURATION   STATUS
run-kuadrantctl-taskrun   32 seconds ago   17s        Succeeded
```

```bash
tkn tr logs run-kuadrantctl-taskrun -f -n petstore

[clone] Cloning into '/workspace/source'...
[clone] Already on 'main'
[clone] Your branch is up to date with 'origin/main'.

[download-kuadrantctl]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[download-kuadrantctl]                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 21.4M  100 21.4M    0     0  12.7M      0  0:00:01  0:00:01 --:--:-- 21.2M

[run-kuadrantctl] kind: AuthPolicy
[run-kuadrantctl] apiVersion: kuadrant.io/v1beta2
[run-kuadrantctl] metadata:
[run-kuadrantctl]   name: petstore
[run-kuadrantctl]   namespace: petstore
[run-kuadrantctl]   creationTimestamp: null
[run-kuadrantctl]   labels:
[run-kuadrantctl]     deployment: petstore
[run-kuadrantctl]     owner: jbloggs
[run-kuadrantctl] spec:
[run-kuadrantctl]   targetRef:
[run-kuadrantctl]     group: gateway.networking.k8s.io
[run-kuadrantctl]     kind: HTTPRoute
[run-kuadrantctl]     name: petstore
[run-kuadrantctl]     namespace: petstore
[run-kuadrantctl]   routeSelectors:
[run-kuadrantctl]     - matches:
[run-kuadrantctl]         - path:
[run-kuadrantctl]             type: Exact
[run-kuadrantctl]             value: /api/v3/store/admin
[run-kuadrantctl]           method: GET
[run-kuadrantctl]   rules:
[run-kuadrantctl]     authentication:
[run-kuadrantctl]       storeAdmin_api_key:
[run-kuadrantctl]         credentials:
[run-kuadrantctl]           customHeader:
[run-kuadrantctl]             name: api_key
[run-kuadrantctl]         apiKey:
[run-kuadrantctl]           selector:
[run-kuadrantctl]             matchLabels:
[run-kuadrantctl]               kuadrant.io/apikeys-by: api_key
[run-kuadrantctl]         routeSelectors:
[run-kuadrantctl]           - matches:
[run-kuadrantctl]               - path:
[run-kuadrantctl]                   type: Exact
[run-kuadrantctl]                   value: /api/v3/store/admin
[run-kuadrantctl]                 method: GET
[run-kuadrantctl] status: {}
[run-kuadrantctl] kind: RateLimitPolicy
[run-kuadrantctl] apiVersion: kuadrant.io/v1beta2
[run-kuadrantctl] metadata:
[run-kuadrantctl]   name: petstore
[run-kuadrantctl]   namespace: petstore
[run-kuadrantctl]   creationTimestamp: null
[run-kuadrantctl]   labels:
[run-kuadrantctl]     deployment: petstore
[run-kuadrantctl]     owner: jbloggs
[run-kuadrantctl] spec:
[run-kuadrantctl]   targetRef:
[run-kuadrantctl]     group: gateway.networking.k8s.io
[run-kuadrantctl]     kind: HTTPRoute
[run-kuadrantctl]     name: petstore
[run-kuadrantctl]     namespace: petstore
[run-kuadrantctl]   limits:
[run-kuadrantctl]     getInventory:
[run-kuadrantctl]       routeSelectors:
[run-kuadrantctl]         - matches:
[run-kuadrantctl]             - path:
[run-kuadrantctl]                 type: Exact
[run-kuadrantctl]                 value: /api/v3/store/inventory
[run-kuadrantctl]               method: GET
[run-kuadrantctl]       rates:
[run-kuadrantctl]         - limit: 10
[run-kuadrantctl]           duration: 10
[run-kuadrantctl]           unit: second
[run-kuadrantctl]     loginUser:
[run-kuadrantctl]       routeSelectors:
[run-kuadrantctl]         - matches:
[run-kuadrantctl]             - path:
[run-kuadrantctl]                 type: Exact
[run-kuadrantctl]                 value: /api/v3/user/login
[run-kuadrantctl]               method: GET
[run-kuadrantctl]       rates:
[run-kuadrantctl]         - limit: 2
[run-kuadrantctl]           duration: 10
[run-kuadrantctl]           unit: second
[run-kuadrantctl] status: {}
[run-kuadrantctl] kind: HTTPRoute
[run-kuadrantctl] apiVersion: gateway.networking.k8s.io/v1beta1
[run-kuadrantctl] metadata:
[run-kuadrantctl]   name: petstore
[run-kuadrantctl]   namespace: petstore
[run-kuadrantctl]   creationTimestamp: null
[run-kuadrantctl]   labels:
[run-kuadrantctl]     deployment: petstore
[run-kuadrantctl]     owner: jbloggs
[run-kuadrantctl] spec:
[run-kuadrantctl]   parentRefs:
[run-kuadrantctl]     - kind: Gateway
[run-kuadrantctl]       namespace: kuadrant-multi-cluster-gateways
[run-kuadrantctl]       name: prod-web
[run-kuadrantctl]   hostnames:
[run-kuadrantctl]     - petstore.${KUADRANT_ZONE_ROOT_DOMAIN}
[run-kuadrantctl]   rules:
[run-kuadrantctl]     - matches:
[run-kuadrantctl]         - path:
[run-kuadrantctl]             type: Exact
[run-kuadrantctl]             value: /api/v3/store/admin
[run-kuadrantctl]           method: GET
[run-kuadrantctl]       backendRefs:
[run-kuadrantctl]         - name: petstore
[run-kuadrantctl]           namespace: petstore
[run-kuadrantctl]           port: 8080
[run-kuadrantctl]     - matches:
[run-kuadrantctl]         - path:
[run-kuadrantctl]             type: Exact
[run-kuadrantctl]             value: /api/v3/store/inventory
[run-kuadrantctl]           method: GET
[run-kuadrantctl]       backendRefs:
[run-kuadrantctl]         - name: petstore
[run-kuadrantctl]           namespace: petstore
[run-kuadrantctl]           port: 8080
[run-kuadrantctl]     - matches:
[run-kuadrantctl]         - path:
[run-kuadrantctl]             type: Exact
[run-kuadrantctl]             value: /api/v3/user/login
[run-kuadrantctl]           method: GET
[run-kuadrantctl]       backendRefs:
[run-kuadrantctl]         - name: petstore
[run-kuadrantctl]           namespace: petstore
[run-kuadrantctl]           port: 8080
[run-kuadrantctl] status:
[run-kuadrantctl]   parents: null

[apply-resources] authpolicy.kuadrant.io/petstore unchanged
[apply-resources] httproute.gateway.networking.k8s.io/petstore created
[apply-resources] ratelimitpolicy.kuadrant.io/petstore created
```

2024-03-12 10:15 UTC, merged