OAS generation and Dev Spaces
Kuadrant/kuadrantctl pull request #62
Opened 2024-03-12 17:50 UTC by jasonmadigan

Draft PR

2024-03-12 18:09 UTC, jasonmadigan commented
@david-martin ready for review

2024-03-13 10:09 UTC, jasonmadigan commented
Related docs PR: https://github.com/Kuadrant/docs.kuadrant.io/pull/84

2024-03-13 10:23 UTC, david-martin requested changes
Few small suggestions for ease of following,
otherwise, looks good.
Got through it ok

2024-03-13 10:23 UTC, david-martin commented on doc/openapi-openshift-dev-spaces.md
> +1. Fork the following repository: `https://github.com/Kuadrant/blank-petstore`.
```suggestion
1. Fork the following repository: [https://github.com/Kuadrant/blank-petstore](https://github.com/Kuadrant/blank-petstore).
```

2024-03-13 12:25 UTC, david-martin commented on doc/openapi-openshift-dev-spaces.md
> +    - api_key: []
Yeah, exactly.
The securityScheme one was indented and made copy/paste easy.
The others, I had to copy/paste & fix indent. 
Not major, so I'll defer to your judgement on what seems most reasonable

2024-03-13 12:51 UTC, jasonmadigan commented
@david-martin fixed up

2024-03-14 09:57 UTC, david-martin reviewed
/lgtm
/approve

2024-03-14 11:10 UTC, david-martin approved these changes

2024-03-14 11:11 UTC, merged